import { DISCLAIMER, EVIDENCE_KINDS, VERDICTS } from "@/lib/constants";
import { frameSrc, heatmapUrlFor, layerOf, peakFrameIndex } from "@/lib/analysis";
import { formatBytes, formatClock, formatDateTime, pct } from "@/lib/utils";
import type { Analysis, FrameAnalysis } from "@/types";

const INK = { authentic: "#0b7a4b", suspicious: "#a86300", manipulated: "#b3202f" } as const;

function Section({ n, title, children }: { n: string; title: string; children: React.ReactNode }) {
  return (
    <section className="report-section mt-9">
      <h2 className="flex items-baseline gap-3 border-b border-neutral-900 pb-1.5 font-mono text-[11px] font-medium uppercase tracking-[0.14em] text-neutral-900">
        <span className="text-neutral-500">{n}</span>
        {title}
      </h2>
      <div className="mt-4">{children}</div>
    </section>
  );
}

function Rows({ rows }: { rows: [string, React.ReactNode][] }) {
  return (
    <dl className="divide-y divide-neutral-200 border-y border-neutral-200">
      {rows.map(([k, v]) => (
        <div key={k} className="grid grid-cols-[150px_1fr] gap-4 py-2 text-[12.5px]">
          <dt className="font-mono text-[10px] uppercase tracking-wider text-neutral-500">{k}</dt>
          <dd className="break-all font-mono text-neutral-900">{v}</dd>
        </div>
      ))}
    </dl>
  );
}

function Figure({ a, f, heat, caption }: { a: Analysis; f: FrameAnalysis; heat?: boolean; caption: string }) {
  const ev = a.evidence.filter((e) => (e.frameIndex ?? 0) === f.index);
  const heatUrl = heat ? heatmapUrlFor(a, f) : undefined;
  return (
    <figure className="report-avoid-break">
      <div className="relative overflow-hidden bg-neutral-900" style={{ aspectRatio: `${a.media.width ?? 4} / ${a.media.height ?? 3}` }}>
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src={frameSrc(a, f)} alt="" className="absolute inset-0 size-full object-cover" />
        {/* eslint-disable-next-line @next/next/no-img-element */}
        {heatUrl && <img src={heatUrl} alt="" className="absolute inset-0 size-full object-cover opacity-70" />}
        {ev.flatMap((e) => e.regions.map((r, i) => <span key={`${e.id}${i}`} className="absolute border border-red-400" style={{ left: `${r.x * 100}%`, top: `${r.y * 100}%`, width: `${r.w * 100}%`, height: `${r.h * 100}%` }} />))}
      </div>
      <figcaption className="mt-1.5 font-mono text-[10px] uppercase tracking-wider text-neutral-500">{caption}</figcaption>
    </figure>
  );
}

/** A4-style forensic report. Styled for both screen and print. */
export function ReportDocument({ analysis: a }: { analysis: Analysis }) {
  const { result, media, model } = { result: a.result, media: a.media, model: a.result.model };
  const v = VERDICTS[result.verdict];
  const isVideo = media.kind === "video";
  const flagged = a.frames.filter((f) => f.flagged).slice(0, 4);
  const evidenceFrames = flagged.length ? flagged : [a.frames[peakFrameIndex(a)]];
  const layers = (["frequency", "compression", "noise"] as const).map((id) => layerOf(a, id)).filter((l) => l?.dataUrl);

  return (
    <article className="report-paper mx-auto w-full max-w-[860px] bg-white px-6 py-8 text-neutral-900 shadow-2xl sm:px-12 sm:py-12 print:max-w-none print:p-0 print:shadow-none">
      {result.simulated && (
        <div className="mb-6 border border-amber-700/60 bg-amber-50 px-4 py-2.5 font-mono text-[10.5px] font-medium uppercase tracking-wider text-amber-900">
          Simulated demonstration report — generated by the VERA demo engine. Not a trained detection model. Not for evidentiary use.
        </div>
      )}
      <header className="flex items-start justify-between gap-6 border-b-2 border-neutral-900 pb-5">
        <div>
          <div className="flex items-center gap-3">
            <svg width="26" height="26" viewBox="0 0 32 32" fill="none" aria-hidden><path d="M2 10V2h8M22 2h8v8M30 22v8h-8M10 30H2v-8" stroke="#0a0a0a" strokeWidth="1.6" /><path d="M9 9l7 14" stroke="#0a0a0a" strokeWidth="2" /><path d="M23 9l-7 14" stroke="#0891b2" strokeWidth="2" /></svg>
            <span className="text-[17px] font-semibold tracking-[0.28em]">VERA</span>
          </div>
          <h1 className="mt-5 font-display text-[40px] leading-none tracking-tight sm:text-5xl">Forensic Analysis Report</h1>
        </div>
        <dl className="shrink-0 space-y-1 text-right font-mono text-[10.5px] uppercase text-neutral-600">
          <div><dt className="inline text-neutral-400">Report </dt><dd className="inline font-medium text-neutral-900">{a.id}</dd></div>
          <div><dt className="inline text-neutral-400">Issued </dt><dd className="inline">{formatDateTime(a.createdAt)}</dd></div>
          <div><dt className="inline text-neutral-400">Node </dt><dd className="inline">{model.node}</dd></div>
        </dl>
      </header>

      <Section n="01" title="Overall assessment">
        <div className="report-avoid-break grid gap-6 border p-5 sm:grid-cols-[1fr_auto]" style={{ borderColor: INK[result.verdict] }}>
          <div>
            <p className="font-mono text-[10px] uppercase tracking-[0.16em] text-neutral-500">Authenticity assessment</p>
            <p className="font-display mt-2 text-[44px] leading-none" style={{ color: INK[result.verdict] }}>{v.label}</p>
            <p className="mt-2 font-mono text-[11px] uppercase tracking-wider">{v.subtitle}</p>
          </div>
          <dl className="grid grid-cols-2 gap-x-8 gap-y-3 font-mono sm:text-right">
            <div><dt className="text-[10px] uppercase text-neutral-500">Model confidence</dt><dd className="text-2xl font-medium">{pct(result.confidence)}</dd></div>
            <div><dt className="text-[10px] uppercase text-neutral-500">Manipulation score</dt><dd className="text-2xl font-medium">{result.manipulationScore.toFixed(3)}</dd></div>
          </dl>
        </div>
        <div className="mt-4 space-y-2.5 text-[13px] leading-relaxed text-neutral-700">
          {result.explanation.map((p, i) => <p key={i}>{p}</p>)}
        </div>
        <p className="mt-4 border-l-2 border-neutral-900 pl-3 text-[12px] italic leading-relaxed text-neutral-600">{DISCLAIMER}</p>
      </Section>

      <Section n="02" title="Media information">
        <Rows rows={[
          ["Filename", media.filename],
          ["Media type", `${media.kind.toUpperCase()} · ${media.mimeType}`],
          ["File size", formatBytes(media.sizeBytes)],
          ["Resolution", media.width ? `${media.width} × ${media.height} px` : "—"],
          ...(isVideo ? ([["Duration", formatClock(media.durationSec ?? 0, true)], ["Frame count", media.frameCount ? `≈ ${media.frameCount.toLocaleString()} (estimated at ${media.fps} fps)` : "—"]] as [string, string][]) : []),
          ["SHA-256", media.sha256],
          ["Analysis timestamp", formatDateTime(a.createdAt)],
        ]} />
      </Section>

      <Section n="03" title="Detected signals">
        <table className="w-full text-left text-[12.5px]">
          <thead><tr className="border-b border-neutral-300 font-mono text-[10px] uppercase tracking-wider text-neutral-500"><th className="py-2 font-normal">Signal</th><th className="w-[44%] font-normal">Contribution</th><th className="w-16 text-right font-normal">Score</th><th className="w-16 text-right font-normal">Weight</th></tr></thead>
          <tbody>
            {result.signals.map((s) => (
              <tr key={s.key} className="border-b border-neutral-200 align-middle">
                <td className="py-2.5"><span className="font-mono text-[11px] uppercase">{s.label}</span><span className="block text-[11px] text-neutral-500">{s.description}</span></td>
                <td>{s.applicable ? <div className="h-2 bg-neutral-200"><div className="h-full" style={{ width: `${s.score * 100}%`, backgroundColor: INK[result.verdict] }} /></div> : <span className="font-mono text-[10px] uppercase text-neutral-400">Not applicable</span>}</td>
                <td className="text-right font-mono">{s.applicable ? pct(s.score, 0) : "—"}</td>
                <td className="text-right font-mono text-neutral-500">{s.applicable ? pct(s.weight, 0) : "—"}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </Section>

      <Section n="04" title="Forensic evidence">
        {a.evidence.length ? (
          <table className="w-full text-left text-[12.5px]">
            <thead><tr className="border-b border-neutral-300 font-mono text-[10px] uppercase tracking-wider text-neutral-500"><th className="w-8 py-2 font-normal">#</th><th className="font-normal">Observation</th><th className="w-24 font-normal">{isVideo ? "Time" : "Scope"}</th><th className="w-16 text-right font-normal">Severity</th></tr></thead>
            <tbody>
              {a.evidence.map((e, i) => (
                <tr key={e.id} className="report-avoid-break border-b border-neutral-200 align-top">
                  <td className="py-2.5 font-mono text-neutral-400">{String(i + 1).padStart(2, "0")}</td>
                  <td className="py-2.5 pr-4"><span className="font-mono text-[10.5px] font-medium uppercase" style={{ color: INK[result.verdict] }}>{EVIDENCE_KINDS[e.kind].label}</span><span className="mt-0.5 block font-medium">{e.title}</span><span className="mt-0.5 block text-[11.5px] leading-relaxed text-neutral-600">{e.description}</span></td>
                  <td className="py-2.5 font-mono text-[11px]">{isVideo && e.timestampSec != null ? `${formatClock(e.timestampSec, true)} · F${(e.frameIndex ?? 0) + 1}` : e.regions.length ? "Regional" : "Global"}</td>
                  <td className="py-2.5 text-right font-mono">{pct(e.severity, 0)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        ) : <p className="text-[13px] text-neutral-600">No notable findings were recorded.</p>}
        <p className="mt-3 text-[11.5px] text-neutral-500">Individual observations do not prove manipulation. Each is one contribution to the overall assessment.</p>
      </Section>

      <Section n="05" title="Evidence frames & heatmaps">
        <div className="grid grid-cols-2 gap-4">
          {evidenceFrames.map((f) => (
            <div key={f.index} className="contents">
              <Figure a={a} f={f} caption={`${isVideo ? `Frame ${f.index + 1} · ${formatClock(f.timestampSec, true)}` : "Source image"} · flagged regions${result.simulated ? " (simulated)" : ""}`} />
              {heatmapUrlFor(a, f) && <Figure a={a} f={f} heat caption={`Heatmap overlay${result.simulated ? " (simulated)" : ""}`} />}
            </div>
          ))}
        </div>
      </Section>

      {layers.length > 0 && (
        <Section n="06" title="Supplementary analyses">
          <div className="grid grid-cols-3 gap-4">
            {layers.map((l) => (
              <figure key={l!.id} className="report-avoid-break">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img src={l!.dataUrl} alt="" className="aspect-square w-full bg-neutral-900 object-cover" />
                <figcaption className="mt-1.5 font-mono text-[10px] uppercase tracking-wider text-neutral-500">{l!.label} · {l!.provenance}</figcaption>
              </figure>
            ))}
          </div>
        </Section>
      )}

      <Section n="07" title="Model information">
        <Rows rows={[
          ["Model", `${model.name} ${model.version}`],
          ["Family", model.family],
          ["Framework", model.framework],
          ["Input resolution", model.inputResolution],
          ["Inference latency", `${model.latencyMs} ms`],
          ["Analysis node", model.node],
          ["Result provenance", model.simulated ? "SIMULATED — no trained weights" : "Trained model inference"],
          ...(model.ensemble.length ? ([["Components", <ul key="c" className="space-y-0.5">{model.ensemble.map((m) => <li key={m}>{m}</li>)}</ul>]] as [string, React.ReactNode][]) : []),
        ]} />
      </Section>

      <Section n="08" title="Limitations">
        <ul className="list-disc space-y-1.5 pl-5 text-[12.5px] leading-relaxed text-neutral-700">
          {result.limitations.map((l) => <li key={l}>{l}</li>)}
        </ul>
      </Section>

      <Section n="09" title="Disclaimer">
        <p className="text-[12px] leading-relaxed text-neutral-600">
          This report presents the output of an automated, probabilistic analysis. Automated detection can produce false positives and false negatives, and its output should be reviewed by a qualified human analyst alongside provenance, context and the original source. {DISCLAIMER}
          {result.simulated && " This particular report was produced by a demonstration engine that does not inspect media for manipulation; its assessments are simulated."}
        </p>
      </Section>

      <footer className="mt-10 flex items-center justify-between border-t border-neutral-300 pt-3 font-mono text-[9.5px] uppercase tracking-wider text-neutral-400">
        <span>VERA · Media Forensics</span>
        <span>{a.id}</span>
        <span>SHA-256 {media.sha256.slice(0, 12)}…</span>
      </footer>
    </article>
  );
}
